// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package models


case class Type(value: models.RequirementTypes,
  isFeature: Option[Boolean] = None)


case class Parent(refId: String)

trait RequirementTypes

object RequirementTypes {
  def fromString(value: String, scope: scala.xml.NamespaceBinding): RequirementTypes = value match {
    case "business" => Business
    case "success-criteria" => SuccessCriteria
    case "assumption" => Assumption
    case "constraint" => Constraint
    case "functional" => Functional
    case "non-functional" => NonFunctional
    case "architectural" => Architectural
    case "technical" => Technical
    case "inverse" => Inverse

  }
}

case object Business extends RequirementTypes { override def toString = "business" }
case object SuccessCriteria extends RequirementTypes { override def toString = "success-criteria" }
case object Assumption extends RequirementTypes { override def toString = "assumption" }
case object Constraint extends RequirementTypes { override def toString = "constraint" }
case object Functional extends RequirementTypes { override def toString = "functional" }
case object NonFunctional extends RequirementTypes { override def toString = "non-functional" }
case object Architectural extends RequirementTypes { override def toString = "architectural" }
case object Technical extends RequirementTypes { override def toString = "technical" }
case object Inverse extends RequirementTypes { override def toString = "inverse" }

trait Strength

object Strength {
  def fromString(value: String, scope: scala.xml.NamespaceBinding): Strength = value match {
    case "shall" => Shall
    case "should" => Should
    case "may" => May

  }
}

case object Shall extends Strength { override def toString = "shall" }
case object Should extends Strength { override def toString = "should" }
case object May extends Strength { override def toString = "may" }


case class RequirementType(annotation: Seq[models.AnnotationType] = Nil,
  title: Option[models.TitleType] = None,
  description: models.DescriptionType,
  author: Option[String] = None,
  classification: Option[models.ClassificationType] = None,
  parent: Option[models.Parent] = None,
  reqRef: Seq[Option[models.RequirementRefType]] = Nil,
  stakeholderRef: Seq[Option[models.StakeholderRefType]] = Nil,
  externalLink: Seq[Option[models.ExternalLinkType]] = Nil,
  any: Seq[scalaxb.DataRecord[Any]] = Nil,
  id: String,
  version: Double,
  strength: models.Strength,
  creationDate: String,
  modificationDate: String,
  attributes: Map[String, scalaxb.DataRecord[Any]])


case class TitleType(mixed: Seq[scalaxb.DataRecord[Any]] = Nil)

trait TitleTypeOption

case class DescriptionType(mixed: Seq[scalaxb.DataRecord[Any]] = Nil,
  attributes: Map[String, scalaxb.DataRecord[Any]])

trait DescriptionTypeOption

case class NarrativeType(value: String)


case class TaxonomyType(value: String,
  classifier: String)


case class ClassificationType(typeValue: models.Type,
  status: models.StatusType,
  packageValue: Seq[scalaxb.DataRecord[Any]] = Nil,
  taxonomy: Seq[models.TaxonomyType] = Nil,
  any: Seq[scalaxb.DataRecord[Any]] = Nil,
  attributes: Map[String, scalaxb.DataRecord[Any]])


case class PackageType(value: String)

trait StatusType

object StatusType {
  def fromString(value: String, scope: scala.xml.NamespaceBinding): StatusType = value match {
    case "proposed" => Proposed
    case "agreed" => Agreed
    case "onhold" => Onhold
    case "rejected" => Rejected
    case "withdrawn" => Withdrawn
    case "implemented" => Implemented
    case "partially-implemented" => PartiallyImplemented
    case "operational" => Operational

  }
}

case object Proposed extends StatusType { override def toString = "proposed" }
case object Agreed extends StatusType { override def toString = "agreed" }
case object Onhold extends StatusType { override def toString = "onhold" }
case object Rejected extends StatusType { override def toString = "rejected" }
case object Withdrawn extends StatusType { override def toString = "withdrawn" }
case object Implemented extends StatusType { override def toString = "implemented" }
case object PartiallyImplemented extends StatusType { override def toString = "partially-implemented" }
case object Operational extends StatusType { override def toString = "operational" }

trait AudienceType

object AudienceType {
  def fromString(value: String, scope: scala.xml.NamespaceBinding): AudienceType = value match {
    case "all" => AllType
    case "internal" => Internal
    case "client" => Client
    case "requirements" => RequirementsValue
    case "development" => Development
    case "design" => Design
    case "test" => Test

  }
}

case object AllType extends AudienceType { override def toString = "all" }
case object Internal extends AudienceType { override def toString = "internal" }
case object Client extends AudienceType { override def toString = "client" }
case object RequirementsValue extends AudienceType { override def toString = "requirements" }
case object Development extends AudienceType { override def toString = "development" }
case object Design extends AudienceType { override def toString = "design" }
case object Test extends AudienceType { override def toString = "test" }


case class ActorRefType(refId: String) extends ReferenceTypeGroupOption


case class StakeholderRefType(refId: String) extends ReferenceTypeGroupOption


case class ExternalLinkType(refId: String,
  typeValue: String,
  href: Option[String] = None)


case class DocumentHistoryType(version: Seq[models.VersionType] = Nil,
  any: Seq[scalaxb.DataRecord[Any]] = Nil,
  currentVersion: String,
  attributes: Map[String, scalaxb.DataRecord[Any]])


case class VersionType(revision: Double,
  author: String,
  changeDate: String,
  description: models.DescriptionType,
  any: Seq[scalaxb.DataRecord[Any]] = Nil,
  attributes: Map[String, scalaxb.DataRecord[Any]])


/** when referencing an existing requirement
*/
case class RequirementRefType(value: String,
  refId: String) extends ReferenceTypeGroupOption

trait Stereotype

object Stereotype {
  def fromString(value: String, scope: scala.xml.NamespaceBinding): Stereotype = value match {
    case "include" => Include
    case "extend" => Extend
    case "generalize" => Generalize
    case "invoke" => Invoke
    case "precedes" => Precedes

  }
}

case object Include extends Stereotype { override def toString = "include" }
case object Extend extends Stereotype { override def toString = "extend" }
case object Generalize extends Stereotype { override def toString = "generalize" }
case object Invoke extends Stereotype { override def toString = "invoke" }
case object Precedes extends Stereotype { override def toString = "precedes" }


/** Used when referencing a use-case
*/
case class UseCaseRefType(value: String,
  refId: String,
  stereotype: Option[models.Stereotype] = None) extends ReferenceTypeGroupOption


/** when referencing an existing requirement
*/
case class ReleaseRefType(value: String,
  refId: String)


/** Represents a collection of referenced requirements that are logically grouped together for documentation purposes
*/
case class RequirementsCollectionType(reqRef: Seq[Option[models.RequirementRefType]] = Nil,
  any: Seq[scalaxb.DataRecord[Any]] = Nil,
  attributes: Map[String, scalaxb.DataRecord[Any]])


/** Re-usable data type that can be inserted elsewhere within other types to
  represent a clarification. The clarification should be a wholly owned subsiduary
  of the enclosing type instance.
*/
case class AnnotationType(description: models.DescriptionType,
  author: String,
  intendedAudience: models.AudienceType,
  creationDate: Option[String] = None,
  comments: Option[models.CommentsType] = None,
  any: Seq[scalaxb.DataRecord[Any]] = Nil,
  attributes: Map[String, scalaxb.DataRecord[Any]])


case class CommentsType(comment: Seq[models.CommentType] = Nil,
  any: Seq[scalaxb.DataRecord[Any]] = Nil)


/** Re-usable block that represents a comment.
*/
case class CommentType(description: Option[models.DescriptionType] = None,
  commentAuthor: Option[String] = None,
  commentDate: Option[String] = None,
  any: Seq[scalaxb.DataRecord[Any]] = Nil)


/** Describes a stakeholder of a requirement and/or use-case.
*/
case class StakeholderType(title: models.TitleType,
  description: models.DescriptionType,
  role: String,
  representative: Seq[String] = Nil,
  any: Seq[scalaxb.DataRecord[Any]] = Nil,
  id: String,
  attributes: Map[String, scalaxb.DataRecord[Any]])

trait ReferenceTypeGroupOption
