// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package models


case class Glossary(entry: Seq[models.GlossaryEntryType] = Nil,
  any: Seq[scalaxb.DataRecord[Any]] = Nil,
  modelu45version: String,
  attributes: Map[String, scalaxb.DataRecord[Any]])


case class GlossaryEntryType(title: models.TitleType,
  abbreviation: Option[String] = None,
  description: models.NarrativeType,
  any: Seq[scalaxb.DataRecord[Any]] = Nil,
  attributes: Map[String, scalaxb.DataRecord[Any]])

