// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package models


case class Requirements(req: Seq[models.RequirementType] = Nil,
  any: Seq[scalaxb.DataRecord[Any]] = Nil,
  modelu45version: String,
  attributes: Map[String, scalaxb.DataRecord[Any]])

