// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package models


case class Stakeholders(stakeholder: Seq[models.StakeholderType] = Nil,
  any: Seq[scalaxb.DataRecord[Any]] = Nil,
  modelu45version: String,
  attributes: Map[String, scalaxb.DataRecord[Any]])

