// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package models


/** Container for all the trace report information.
*/
case class TraceReportType(artefact: Seq[models.ArtefactType] = Nil,
  created: String,
  baseUri: Option[java.net.URI] = None,
  baseId: String)

trait Class

object Class {
  def fromString(value: String, scope: scala.xml.NamespaceBinding): Class = value match {
    case "requirement" => Requirement
    case "usecase" => Usecase

  }
}

case object Requirement extends Class { override def toString = "requirement" }
case object Usecase extends Class { override def toString = "usecase" }


case class TraceTo(value: String,
  classValue: Option[models.Class] = None)


/** Represents any external artefact. This may include things such as Java classes, Test cases, documents etc.
*/
case class ArtefactType(id: String,
  location: Option[String] = None,
  traceTo: Seq[models.TraceTo] = Nil,
  status: Option[String] = None,
  typeValue: String,
  uri: Option[String] = None)

trait BuiltInArtefactClassifiersType

object BuiltInArtefactClassifiersType {
  def fromString(value: String, scope: scala.xml.NamespaceBinding): BuiltInArtefactClassifiersType = value match {
    case "java:class" => JavaClass
    case "java:type" => JavaType
    case "java:interface" => JavaInterface
    case "java:method" => JavaMethod
    case "java:member" => JavaMember
    case "java:unknown" => JavaUnknown
    case "test:unit" => TestUnit
    case "test:integration" => TestIntegration
    case "test:performance" => TestPerformance
    case "test:resillience" => TestResillience
    case "test:ui" => TestUi
    case "test:other" => TestOther

  }
}

case object JavaClass extends BuiltInArtefactClassifiersType { override def toString = "java:class" }
case object JavaType extends BuiltInArtefactClassifiersType { override def toString = "java:type" }
case object JavaInterface extends BuiltInArtefactClassifiersType { override def toString = "java:interface" }
case object JavaMethod extends BuiltInArtefactClassifiersType { override def toString = "java:method" }
case object JavaMember extends BuiltInArtefactClassifiersType { override def toString = "java:member" }
case object JavaUnknown extends BuiltInArtefactClassifiersType { override def toString = "java:unknown" }
case object TestUnit extends BuiltInArtefactClassifiersType { override def toString = "test:unit" }
case object TestIntegration extends BuiltInArtefactClassifiersType { override def toString = "test:integration" }
case object TestPerformance extends BuiltInArtefactClassifiersType { override def toString = "test:performance" }
case object TestResillience extends BuiltInArtefactClassifiersType { override def toString = "test:resillience" }
case object TestUi extends BuiltInArtefactClassifiersType { override def toString = "test:ui" }
case object TestOther extends BuiltInArtefactClassifiersType { override def toString = "test:other" }

