// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package models


/** Container for all the trace report information.
*/
case class Traceu45reportType(artefact: Seq[models.ArtefactType] = Nil,
  created: String,
  baseu45uri: Option[java.net.URI] = None,
  baseu45id: String)

trait Class

object Class {
  def fromString(value: String, scope: scala.xml.NamespaceBinding): Class = value match {
    case "requirement" => Requirement
    case "usecase" => Usecase

  }
}

case object Requirement extends Class { override def toString = "requirement" }
case object Usecase extends Class { override def toString = "usecase" }


case class Traceu45to(value: String,
  classValue: Option[models.Class] = None)


/** Represents any external artefact. This may include things such as Java classes, Test cases, documents etc.
*/
case class ArtefactType(id: String,
  location: Option[String] = None,
  traceu45to: Seq[models.Traceu45to] = Nil,
  status: Option[String] = None,
  typeValue: String,
  uri: Option[String] = None)

trait Builtu45inu45artefactu45classifiersType

object Builtu45inu45artefactu45classifiersType {
  def fromString(value: String, scope: scala.xml.NamespaceBinding): Builtu45inu45artefactu45classifiersType = value match {
    case "java:class" => Javau58class
    case "java:type" => Javau58type
    case "java:interface" => Javau58interface
    case "java:method" => Javau58method
    case "java:member" => Javau58member
    case "java:unknown" => Javau58unknown
    case "test:unit" => Testu58unit
    case "test:integration" => Testu58integration
    case "test:performance" => Testu58performance
    case "test:resillience" => Testu58resillience
    case "test:ui" => Testu58ui
    case "test:other" => Testu58other

  }
}

case object Javau58class extends Builtu45inu45artefactu45classifiersType { override def toString = "java:class" }
case object Javau58type extends Builtu45inu45artefactu45classifiersType { override def toString = "java:type" }
case object Javau58interface extends Builtu45inu45artefactu45classifiersType { override def toString = "java:interface" }
case object Javau58method extends Builtu45inu45artefactu45classifiersType { override def toString = "java:method" }
case object Javau58member extends Builtu45inu45artefactu45classifiersType { override def toString = "java:member" }
case object Javau58unknown extends Builtu45inu45artefactu45classifiersType { override def toString = "java:unknown" }
case object Testu58unit extends Builtu45inu45artefactu45classifiersType { override def toString = "test:unit" }
case object Testu58integration extends Builtu45inu45artefactu45classifiersType { override def toString = "test:integration" }
case object Testu58performance extends Builtu45inu45artefactu45classifiersType { override def toString = "test:performance" }
case object Testu58resillience extends Builtu45inu45artefactu45classifiersType { override def toString = "test:resillience" }
case object Testu58ui extends Builtu45inu45artefactu45classifiersType { override def toString = "test:ui" }
case object Testu58other extends Builtu45inu45artefactu45classifiersType { override def toString = "test:other" }

